version: '3'
services:
  neo4j:
    image: neo4j
    env_file: neo4j.env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
      - ./neo4j/plugins:/plugins
      - ./data/output:/data-import
  cloudera:
    image: gdelorme/spark-marinewatch
    command: /usr/bin/docker-quickstart
    tty: true
    privileged: true
    hostname: quickstart.cloudera
    volumes:
      - ./data:/workdir/data
      - ./code/mwspark:/workdir/code
